### PR TITLE
Sour pea

### PR DESCRIPTION
**Pull request by younesStrittmatter**
There was an error in the check_mismatch function (it compared the absolute values of the sample levels to the weight in the level declaration). However, I am not sure if this change is compatible with the use of the function in the random-sampler.

### CODE REVIEW

**Comment by mflatt** [comment]
As you suspect, this change breaks the random sampler.

I'm not clear on what the changes are supposed to do. There's a file named "Test_simple.py" where mismatches are reported before the change and not after the change, but it looks to me like mismatches *should* be reported. Given the definition of `block`, the a trial sequence should have pairs of `R` and `L` (in either order), and it should have 50 trials. If `target_side_list` is `[Level('R', 3), Level('L', 3)]` and the `MinimumTrials` constraint is removed, then the trial sequence is valid. So, can you explain more about the goal of the change?

**Comment by younesStrittmatter** [comment]
So in summary: The changes I made are to "normalize" the weighting by dividing through the maximum weight, so that for the test of crossing, this: [Level('R', 3), Level('L', 3)] is equivalent with [Level('R', 1), Level('L', 1)]. In my opinion, the weights are relative, not absolute values (at least for the testing) and shouldn't be dependent on the number of trials in a sequence.

**Comment by mflatt** [comment]
> For example if the levels R and L are both weighted 1, it shouldn't matter how many trials there are for the crossing. The only thing that matters, is that R and L appear in the same frequency

I can imagine that's an experiment that you want to describe, but it isn't what the SweetPea experiment description in "Test_simple.py" means. SweetPea doesn't currently have a notion of relative weights like that. You'd have to pick a number of trials and specify weights to match:

```
def make_experiment(trial_count):
    target_side_list = [Level('R', trial_count // 2), Level('L', trial_count // 2)]
    target_side = Factor(name='target side', initial_levels=target_side_list)
    design = [target_side]
    crossing = [target_side]
    constraints = []
    return CrossBlock(design, crossing, constraints)

block = make_experiment(6)
```

> In my opinion

Sorry, but the entire point of SweetPea is that the meaning of an experiment description is not a matter of opinion. :)

**Comment by younesStrittmatter** [comment]
I am sorry, but I either don't understand correctly, or this is not true. For example this:
```
target_side_list = [Level('R',4), Level('L',1)]
target_side = Factor(name='target side', initial_levels=target_side_list)
design = [target_side]
crossing = [target_side]
constraints = [MinimumTrials(10)]
block = CrossBlock(design, crossing, constraints)
experiment = synthesize_trials(block, 1)
print(experiment)
```
results in a trial sequence with 8 R levels and 2 L levels. I don't have to specify the absolute values but the relative ones.

**Comment by mflatt** [comment]
That's an experiment with 4 `R`s and 1 `L` as the first 5 trials, and then another sequence of 5 trials with 4 `R`s and 1 `L`. So, you're right that there's a kind of relative weight there, but `MininumTrials` doesn't mean that the weights are scaled up to match a number of trials. A `MinimumTrials` constraint causes the crossing to be repeated as many times as needed to reach that many trials (and the last repetition can be truncated if the request number is not a multiple of the corssing size).

Perhaps more helpfully, SweetPea could get new constructs to let you say the thing you want to say. But that's not what the current constructs mean.

**Comment by younesStrittmatter** [comment]
I think I kinda get what you mean. I didn't know how the internals work, I just assumed, that the weights are relative, since they "scale" with the number of trials needed. Another example would be this: 
```
target_side_list = [Level('R',1), Level('L',1)]
other_factor = Factor('other', initial_levels=['a','b'])
target_side = Factor(name='target side', initial_levels=target_side_list)
design = [target_side, other_factor]
crossing = [target_side, other_factor]
block = CrossBlock(design, crossing, [])
experiment = synthesize_trials(block, 1)
print(experiment)
```
results in a trial sequence with 2 R levels and 2 L levels (as it should). What do you think would be the best way to go forward with the checking anyways? Somehow adjust the weights before checking?

**Comment by mflatt** [comment]
I would use the `make_experiment` approach above, where you have a target number of trials and get an experiment description to match that.

This is not meant to be a question about how internals work, but about what `MinimumTrials` and weights mean. If it's supposed to mean something different than it does right now (i.e., a mismatch between what experimenters need and what the implementers understood), then we should certainly address that — but keeping generation and checking consistent.

**Comment by younesStrittmatter** [comment]
Okay. That makes a lot of sense. Thanks a lot for clarifying!!! I think this is worth discussing in a meeting, so we can address it if necessary. For example, the concatenation of trial sequences with minimumTrials is at least worth mentioning since it does introduce autocorrelation (especially if there are only a few factors or levels) and constraints the maximum number of repeats in a (for me) unexpected way. 
```
target_side_list = ['R', 'L']
target_side = Factor(name='target side', initial_levels=target_side_list)
constraints = [MinimumTrials(30), AtLeastKInARow(2, target_side)]

design = [target_side]
crossing = [target_side]
block = CrossBlock(design, crossing, constraints)
experiment = synthesize_trials(block, 1, UniformGen)
print(experiment)
```
results in an empty trial sequence (since there can not be 2 repeats in the "sequence block" that the whole sequence is build upon). But my guess is that this is not intuitive for most users. It is easy to fix (by adjusting the weights as I now understand), but still, I think this might cause user errors.

**Pull request closed without merging**
